# yaml-language-server: $schema=https://aka.ms/winget-manifest.defaultLocale.1.12.0.schema.json

PackageIdentifier: asciimoo.hister
PackageVersion: 0.9.0
PackageLocale: en-US
Publisher: asciimoo
PublisherUrl: https://github.com/asciimoo
PublisherSupportUrl: https://github.com/asciimoo/hister/issues
Author: Adam Tauber
PackageName: Hister
PackageUrl: https://github.com/asciimoo/hister
License: AGPL-3.0
LicenseUrl: https://github.com/asciimoo/hister/blob/v0.9.0/LICENSE
ShortDescription: Your own search engine – Full-text search across your files, visited sites and beyond.
Description: |-
  Hister is a versatile, privacy-focused web search engine designed to index the full content of visited web pages locally. Unlike traditional search engines, it allows you to find specific information within your own browsing history using full-text indexing.
ReleaseNotes: |-
  What's Changed
  Added local file indexing support
  Other contributions
  - [fix] fix all golangci-lint errcheck and unused warnings by @FlameFlag in #182
  - [enh] add dependabot support by @FlameFlag in #185
  - Update Nix hashes by @github-actions[bot] in #200
  - [enh] make ext use same design as app and website by @FlameFlag in #199
  - [fix] fix Docker publish workflow and Dockerfile by @FlameFlag in #205
  - [fix] improve list-urls performances and fix missing entries by @scumjr in #206
  - [ci] add PR lint workflow for Go, NPM format, and no merge commits by @FlameFlag in #211
  - [feat] update to vite 8.0.0 and use rolldown by @FlameFlag in #212
  - [fix] patch workspace shebangs in nix frontend derivation by @FlameFlag in #213
  - Update Nix hashes by @github-actions[bot] in #214
  - [ci] add build for hister, @hister/website and @hister/ext for PR's by @FlameFlag in #215
  - feat: add ability to index and view local files by @jamestthompson3 in #210
  - docs: update docs on how local indexing works by @jamestthompson3 in #217
  - [fix] nix/package.nix add files package to build inputs by @FlameFlag in #226
ReleaseNotesUrl: https://github.com/asciimoo/hister/releases/tag/v0.9.0
Documentations:
- DocumentLabel: Documentation
  DocumentUrl: https://hister.org/docs
ManifestType: defaultLocale
ManifestVersion: 1.12.0
