# Created using wingetcreate 1.6.1.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.6.0.schema.json

PackageIdentifier: 7zip.7zip.Alpha.msi
PackageVersion: "22.00"
MinimumOSVersion: 10.0.0.0
InstallerType: wix
ReleaseDate: 2022-06-15
Scope: machine
InstallModes:
- interactive
- silent
- silentWithProgress
UpgradeBehavior: install
Commands:
- 7z
FileExtensions:
- 7z
- ar
- arj
- bzip2
- cab
- chm
- cpio
- cramfs
- dmg
- ext
- fat
- gpt
- gzip
- hfs
- ihex
- iso
- lzh
- lzma
- mbr
- msi
- nsis
- ntfs
- qcow2
- rar
- rpm
- squashfs
- tar
- udf
- uefi
- vdi
- vhd
- vmdk
- wim
- xar
- xz
- z
- zip
Installers:
- Architecture: x64
  InstallerUrl: https://www.7-zip.org/a/7z2200-x64.msi
  InstallerSha256: 5C6E1CC0A09DE58131707C332ADD6E30CD299383999B8F047A90335F8066E217
  ProductCode: '{23170F69-40C1-2702-2200-000001000000}'
- Architecture: x86
  InstallerUrl: https://www.7-zip.org/a/7z2200.msi
  InstallerSha256: FA2D9AF8763B898374FC4F44010CF824147369A63730F9CDF2985BD0028C0175
  ProductCode: '{23170F69-40C1-2701-2200-000001000000}'
ManifestType: installer
ManifestVersion: 1.6.0
