# Created using wingetcreate 1.6.1.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.6.0.schema.json

PackageIdentifier: VideoLAN.VLC.win64-arm
PackageVersion: 20240224-0438
InstallerLocale: en-US
InstallerType: wix
ProductCode: '{4F9AB792-187B-47B7-82AB-BC05482F3FA9}'
Installers:
- InstallerUrl: https://artifacts.videolan.org/vlc/nightly-win64-arm-llvm/20240224-0438/vlc-4.0.0-dev-win64-410d5999.msi
  Architecture: arm64
  InstallerSha256: 9F33773C4DDD16818A9C391F41110A670F7689095ACE5DECA6C5DAF3223D1C87
ManifestType: installer
ManifestVersion: 1.6.0
