# yaml-language-server: $schema=https://aka.ms/winget-manifest.defaultLocale.1.12.0.schema.json

PackageIdentifier: asciimoo.hister
PackageVersion: 0.2.0
PackageLocale: en-US
Publisher: asciimoo
PublisherUrl: https://github.com/asciimoo
PublisherSupportUrl: https://github.com/asciimoo/hister/issues
Author: Adam Tauber
PackageName: Hister
PackageUrl: https://github.com/asciimoo/hister
License: AGPL-3.0
LicenseUrl: https://github.com/asciimoo/hister/blob/v0.2.0/LICENSE
ShortDescription: Your own search engine – Full-text search across your files, visited sites and beyond.
Description: |-
  Hister is a versatile, privacy-focused web search engine designed to index the full content of visited web pages locally. Unlike traditional search engines, it allows you to find specific information within your own browsing history using full-text indexing.
ReleaseNotes: |-
  Changelog
  - [fix] add CGO support for release builds
  - [enh] add random tips
  - [mod] mute grey colors
  - [fix] use original query for retrieving priority results
  - [fix] open correct link
  - [fix] trim whitespaces
  - [mod] do not resolve query aliases in history
  - [fix] prevent popup overflow
  - [fix] convert url lowercase in lookup
  - [enh] add readable preview of results
  - [enh] add autocomplete query suggestions
  - [mod] refactor result rendering
  - [enh] add command line tool reference
  - [enh] add priority results for user defined queries
  - [enh] add import command
ReleaseNotesUrl: https://github.com/asciimoo/hister/releases/tag/v0.2.0
Documentations:
- DocumentLabel: Documentation
  DocumentUrl: https://hister.org/docs
ManifestType: defaultLocale
ManifestVersion: 1.12.0
