# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: asciimoo.hister
PackageVersion: 0.2.0
InstallerType: portable
Commands:
- hister
ReleaseDate: 2026-01-19
Installers:
- Architecture: x64
  InstallerUrl: https://github.com/asciimoo/hister/releases/download/v0.2.0/hister_0.2.0_windows_amd64.exe
  InstallerSha256: 883575ef62daa1d35b4715677a14807f2d7715c307b85251908cb3565fa984d6
ManifestType: installer
ManifestVersion: 1.12.0
