# yaml-language-server: $schema=https://aka.ms/winget-manifest.defaultLocale.1.12.0.schema.json

PackageIdentifier: asciimoo.hister
PackageVersion: 0.6.0
PackageLocale: en-US
Publisher: asciimoo
PublisherUrl: https://github.com/asciimoo
PublisherSupportUrl: https://github.com/asciimoo/hister/issues
Author: Adam Tauber
PackageName: Hister
PackageUrl: https://github.com/asciimoo/hister
License: AGPL-3.0
LicenseUrl: https://github.com/asciimoo/hister/blob/v0.6.0/LICENSE
ShortDescription: Your own search engine – Full-text search across your files, visited sites and beyond.
Description: |-
  Hister is a versatile, privacy-focused web search engine designed to index the full content of visited web pages locally. Unlike traditional search engines, it allows you to find specific information within your own browsing history using full-text indexing.
ReleaseNotes: |-
  What's Changed
  - refactor(nix): rewrite packaging following best practices by @XYenon in #114
  - [fix] pressing tab deletes query on no suggestion, fix inconsistent history by @FlameFlag in #117
  - Enhance server configuration documentation and fix documentation layout by @sinsky in #118
  - feat: migrate to npm workspaces for manging frontend by @FlameFlag in #121
  - Part 1/5 of the new redesign by @FlameFlag in #126
  - Part 2/5 of the new redesign by @FlameFlag in #127
  - Part 3/5 of the new redesign by @FlameFlag in #128
  - Part 4/5 of the new redesign by @FlameFlag in #129
  - Part 5/5 of the new redesign by @FlameFlag in #130
  - fix(querybuilder): handle UTF-8 queries in lexer by @yshalsager in #132
  - [refactor] extract dedicated API client package by @FlameFlag in #135
  - [enh] add & use more shadcn-svelte components by @FlameFlag in #134
  - Allow base_url to include subfolder path by @singhAmandeep007 in #133
  - [fix] add client module to nix package inputs by @antifuchs in #137
  - [enh] improve mobile responsiveness & add updated_at timestamps to history by @FlameFlag in #136
  - [fix] fix search results scrolling, input resizing, and keyboard nav by @FlameFlag in #138
  - Update Nix hashes by @github-actions[bot] in #139
  - [enh] re-design the website by @FlameFlag in #140
  - better apply brutalist design on the app by @FlameFlag in #141
  - [enh] redesign rules page with bold brutalist layout by @FlameFlag in #142
  - [fix] {api -> api-docs} page to avoid conflict with the api endpoint by @FlameFlag in #143
  - [enh] redesign api-docs page by @FlameFlag in #144
  - [enh] improve mobile responsiveness by @FlameFlag in #145
  - [enh] add -f to search (csv, json) by @FlameFlag in #148
  - [fix] check skip rules client-side during import by @FlameFlag in #152
  - [fix] pass access token from config to HTTP client by @FlameFlag in #153
  - [refactor] extract mouse handling into dedicated package by @FlameFlag in #160
  - [enh] switch ext to use vite for build by @FlameFlag in #162
  - [enh] redesign docs page by @FlameFlag in #158
ReleaseNotesUrl: https://github.com/asciimoo/hister/releases/tag/v0.6.0
Documentations:
- DocumentLabel: Documentation
  DocumentUrl: https://hister.org/docs
ManifestType: defaultLocale
ManifestVersion: 1.12.0
