# yaml-language-server: $schema=https://aka.ms/winget-manifest.defaultLocale.1.12.0.schema.json

PackageIdentifier: asciimoo.hister
PackageVersion: 0.3.0
PackageLocale: en-US
Publisher: asciimoo
PublisherUrl: https://github.com/asciimoo
PublisherSupportUrl: https://github.com/asciimoo/hister/issues
Author: Adam Tauber
PackageName: Hister
PackageUrl: https://github.com/asciimoo/hister
License: AGPL-3.0
LicenseUrl: https://github.com/asciimoo/hister/blob/v0.3.0/LICENSE
ShortDescription: Your own search engine – Full-text search across your files, visited sites and beyond.
Description: |-
  Hister is a versatile, privacy-focused web search engine designed to index the full content of visited web pages locally. Unlike traditional search engines, it allows you to find specific information within your own browsing history using full-text indexing.
ReleaseNotes: |-
  Changelog
  - Merge branch 'hotkeys'
  - [enh] add option to hide hotkey popup button
  - [enh] add button to show hotkeys popup
  - [enh] show configured hotkeys
  - [enh] add configurable hotkey handling
  - [enh] add reindex command ++ date field for results
  - [fix] do not save search engine links as history items
  - [enh] highlight focused result
  - [enh] update assets
  - [enh] add colors
  - [enh] add banner to help text
  - [enh] add command line search interface
  - [enh] remove utm parameters
  - [fix] maximize image/pre content width in readability popup
  - [enh] handle result open with middle click
  - [doc] simplify description
  - [enh] make sure document is processed before add
  - [enh] add wildcard domain name search
  - [fix] do not match regexp if rule is empty
  - [enh] extend features
  - [fix] typo
  - [enh] automatically redirect to search engine if no results found
  - [enh] extract opened results from search engines (google) and save them as priority results
  - [enh] add !! prefix to open query in configured search engine
  - [fix] handle fetch errors
  - [enh] add csrf protection
  - [enh] add static pubkey to chrome extension
  - [enh] add opensearch.xml
  - [enh] add priority result removal
  - [enh] add fonts
  - [fix] return errors
  - [enh] bump addon version
  - [enh] add error handling
  - [enh] increment check periods if there are no changes
  - [doc] mention chmod
  - [mod] replace ctrl modifier key with alt to avoid conflict with existing keybindings
  - [enh] close popup on pressing escape key
ReleaseNotesUrl: https://github.com/asciimoo/hister/releases/tag/v0.3.0
Documentations:
- DocumentLabel: Documentation
  DocumentUrl: https://hister.org/docs
ManifestType: defaultLocale
ManifestVersion: 1.12.0
